
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace MWebAsk.Models
{
    /// <summary>
    /// The class representing the dbo.Question table.
    /// </summary>
    [Table(Name="dbo.Question")]
    public partial class Question
        : MWebAskEntity
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Question"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public Question()
        {
            OnCreated();
            _userAccount = default(EntityRef<Account>);
            _category = default(EntityRef<Category>);
            _replyList = new EntitySet<Reply>(
                new System.Action<Reply>(this.Attach_ReplyList),
                new System.Action<Reply>(this.Detach_ReplyList));
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _iD = default(long);

        /// <summary>
        /// Gets the ID column value.
        /// </summary>
        [Column(Name="ID", Storage="_iD", DbType="bigint NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public long ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    OnIDChanging(value);
                    OnPropertyChanging("ID");
                    _iD = value;
                    OnPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        
        private string _title;

        /// <summary>
        /// Gets or sets the Title column value.
        /// </summary>
        [Column(Name="Title", Storage="_title", DbType="nvarchar(50) NOT NULL", CanBeNull=false)]
        public string Title
        {
            get { return _title; }
            set
            {
                if (_title != value)
                {
                    OnTitleChanging(value);
                    OnPropertyChanging("Title");
                    _title = value;
                    OnPropertyChanged("Title");
                    OnTitleChanged();
                }
            }
        }
        
        private string _body;

        /// <summary>
        /// Gets or sets the Body column value.
        /// </summary>
        [Column(Name="Body", Storage="_body", DbType="ntext NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
        public string Body
        {
            get { return _body; }
            set
            {
                if (_body != value)
                {
                    OnBodyChanging(value);
                    OnPropertyChanging("Body");
                    _body = value;
                    OnPropertyChanged("Body");
                    OnBodyChanged();
                }
            }
        }
        
        private System.DateTime _addtime;

        /// <summary>
        /// Gets or sets the Addtime column value.
        /// </summary>
        [Column(Name="Addtime", Storage="_addtime", DbType="smalldatetime NOT NULL", CanBeNull=false)]
        public System.DateTime Addtime
        {
            get { return _addtime; }
            set
            {
                if (_addtime != value)
                {
                    OnAddtimeChanging(value);
                    OnPropertyChanging("Addtime");
                    _addtime = value;
                    OnPropertyChanged("Addtime");
                    OnAddtimeChanged();
                }
            }
        }
        
        private System.DateTime _edittime;

        /// <summary>
        /// Gets or sets the Edittime column value.
        /// </summary>
        [Column(Name="Edittime", Storage="_edittime", DbType="smalldatetime NOT NULL", CanBeNull=false)]
        public System.DateTime Edittime
        {
            get { return _edittime; }
            set
            {
                if (_edittime != value)
                {
                    OnEdittimeChanging(value);
                    OnPropertyChanging("Edittime");
                    _edittime = value;
                    OnPropertyChanged("Edittime");
                    OnEdittimeChanged();
                }
            }
        }
        
        private long _userID;

        /// <summary>
        /// Gets or sets the UserID column value.
        /// </summary>
        [Column(Name="UserID", Storage="_userID", DbType="bigint NOT NULL", CanBeNull=false)]
        public long UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (_userAccount.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnUserIDChanging(value);
                    OnPropertyChanging("UserID");
                    _userID = value;
                    OnPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        
        private long _categoryID;

        /// <summary>
        /// Gets or sets the CategoryID column value.
        /// </summary>
        [Column(Name="CategoryID", Storage="_categoryID", DbType="bigint NOT NULL", CanBeNull=false)]
        public long CategoryID
        {
            get { return _categoryID; }
            set
            {
                if (_categoryID != value)
                {
                    if (_category.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnCategoryIDChanging(value);
                    OnPropertyChanging("CategoryID");
                    _categoryID = value;
                    OnPropertyChanged("CategoryID");
                    OnCategoryIDChanged();
                }
            }
        }
        
        private int _hits;

        /// <summary>
        /// Gets or sets the Hits column value.
        /// </summary>
        [Column(Name="Hits", Storage="_hits", DbType="int NOT NULL", CanBeNull=false)]
        public int Hits
        {
            get { return _hits; }
            set
            {
                if (_hits != value)
                {
                    OnHitsChanging(value);
                    OnPropertyChanging("Hits");
                    _hits = value;
                    OnPropertyChanged("Hits");
                    OnHitsChanged();
                }
            }
        }
        
        private int _point;

        /// <summary>
        /// Gets or sets the Point column value.
        /// </summary>
        [Column(Name="Point", Storage="_point", DbType="int NOT NULL", CanBeNull=false)]
        public int Point
        {
            get { return _point; }
            set
            {
                if (_point != value)
                {
                    OnPointChanging(value);
                    OnPropertyChanging("Point");
                    _point = value;
                    OnPropertyChanged("Point");
                    OnPointChanged();
                }
            }
        }
        
        private byte _situation;

        /// <summary>
        /// Gets or sets the Situation column value.
        /// </summary>
        [Column(Name="Situation", Storage="_situation", DbType="tinyint NOT NULL", CanBeNull=false)]
        public byte Situation
        {
            get { return _situation; }
            set
            {
                if (_situation != value)
                {
                    OnSituationChanging(value);
                    OnPropertyChanging("Situation");
                    _situation = value;
                    OnPropertyChanged("Situation");
                    OnSituationChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        
        private EntityRef<Account> _userAccount;

        /// <summary>
        /// Gets or sets the Account association.
        /// </summary>
        [Association(Name="FK_Question_Account", Storage="_userAccount", ThisKey="UserID", OtherKey="ID", IsForeignKey=true)]
        public Account UserAccount
        {
            get { return _userAccount.Entity; }
            set
            {
                Account previousValue = _userAccount.Entity;
                if (previousValue != value || _userAccount.HasLoadedOrAssignedValue == false)
                {
                    OnPropertyChanging("UserAccount");
                    if (previousValue != null)
                    {
                        _userAccount.Entity = null;
                        previousValue.UserQuestionList.Remove(this);
                    }
                    _userAccount.Entity = value;
                    if (value != null)
                    {
                        value.UserQuestionList.Add(this);
                        _userID = value.ID;
                    }
                    else
                    {
                        _userID = default(long);
                    }
                    OnPropertyChanged("UserAccount");
                }
            }
        }
        
        private EntityRef<Category> _category;

        /// <summary>
        /// Gets or sets the Category association.
        /// </summary>
        [Association(Name="FK_Question_Category", Storage="_category", ThisKey="CategoryID", OtherKey="ID", IsForeignKey=true)]
        public Category Category
        {
            get { return _category.Entity; }
            set
            {
                Category previousValue = _category.Entity;
                if (previousValue != value || _category.HasLoadedOrAssignedValue == false)
                {
                    OnPropertyChanging("Category");
                    if (previousValue != null)
                    {
                        _category.Entity = null;
                        previousValue.QuestionList.Remove(this);
                    }
                    _category.Entity = value;
                    if (value != null)
                    {
                        value.QuestionList.Add(this);
                        _categoryID = value.ID;
                    }
                    else
                    {
                        _categoryID = default(long);
                    }
                    OnPropertyChanged("Category");
                }
            }
        }
        
        private EntitySet<Reply> _replyList;
        
        /// <summary>
        /// Gets or sets the Reply association.
        /// </summary>
        [Association(Name="FK_Reply_Question", Storage="_replyList", ThisKey="ID", OtherKey="QuestionID")]
        public EntitySet<Reply> ReplyList
        {
            get { return _replyList; }
            set { _replyList.Assign(value); }
        }
        
        [DebuggerNonUserCodeAttribute()]
        private void Attach_ReplyList(Reply entity)
        {
            OnPropertyChanging(null);
            entity.Question = this;
            OnPropertyChanged(null);
        }
        
        [DebuggerNonUserCodeAttribute()]
        private void Detach_ReplyList(Reply entity)
        {
            OnPropertyChanging(null);
            entity.Question = null;
            OnPropertyChanged(null);
        }
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when ID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIDChanging(long value);
        /// <summary>Called after ID has Changed.</summary>
        partial void OnIDChanged();
        /// <summary>Called when Title is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTitleChanging(string value);
        /// <summary>Called after Title has Changed.</summary>
        partial void OnTitleChanged();
        /// <summary>Called when Body is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnBodyChanging(string value);
        /// <summary>Called after Body has Changed.</summary>
        partial void OnBodyChanged();
        /// <summary>Called when Addtime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnAddtimeChanging(System.DateTime value);
        /// <summary>Called after Addtime has Changed.</summary>
        partial void OnAddtimeChanged();
        /// <summary>Called when Edittime is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnEdittimeChanging(System.DateTime value);
        /// <summary>Called after Edittime has Changed.</summary>
        partial void OnEdittimeChanged();
        /// <summary>Called when UserID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUserIDChanging(long value);
        /// <summary>Called after UserID has Changed.</summary>
        partial void OnUserIDChanged();
        /// <summary>Called when CategoryID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnCategoryIDChanging(long value);
        /// <summary>Called after CategoryID has Changed.</summary>
        partial void OnCategoryIDChanged();
        /// <summary>Called when Hits is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnHitsChanging(int value);
        /// <summary>Called after Hits has Changed.</summary>
        partial void OnHitsChanged();
        /// <summary>Called when Point is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnPointChanging(int value);
        /// <summary>Called after Point has Changed.</summary>
        partial void OnPointChanged();
        /// <summary>Called when Situation is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnSituationChanging(byte value);
        /// <summary>Called after Situation has Changed.</summary>
        partial void OnSituationChanged();
        #endregion
        
    }
}

